/*
 * Copyright (c) 2026 Yamatri Reddy
 * SPDX-License-Identifier: GPL-3.0-only
 */

import { describe, expect, it } from 'vitest';
import {
    alterTableSql,
    autoLayout,
    buildErModel,
    callRoutineSql,
    callStatements,
    capabilitiesOf,
    categoryOfType,
    createIndexSql,
    createRoutineSql,
    createTableSql,
    createTriggerSql,
    createViewSql,
    deleteRowSql,
    designFromMetadata,
    dialectOf,
    dropRoutineSql,
    dropTableSql,
    dropTriggerSql,
    emptyDesign,
    insertRowSql,
    mysqlDialect,
    parametersFromDefinition,
    parseCellInput,
    postgresDialect,
    relationshipsOf,
    selectPageSql,
    setTriggerEnabledSql,
    splitType,
    updateRowSql,
    validateDesign,
    viewQueryFromDefinition,
    type TableDesign,
} from './index';

const users = (): TableDesign => ({
    ...emptyDesign('users'),
    columns: [
        { id: 'a', name: 'id', type: 'int', nullable: false, autoIncrement: true },
        { id: 'b', name: 'email', type: 'varchar', length: '255', nullable: false },
        { id: 'c', name: 'bio', type: 'text', nullable: true, default: "'none'" },
    ],
    primaryKey: ['id'],
    uniques: [{ columns: ['email'] }],
    indexes: [{ name: 'idx_users_bio', columns: [{ name: 'bio' }], unique: false }],
});

describe('capabilities', () => {
    it('offers each engine only what it has', () => {
        expect(capabilitiesOf('postgresql')).toMatchObject({
            supportsSchemas: true,
            supportsSequences: true,
            supportsERDiagram: true,
        });
        expect(capabilitiesOf('mysql')).toMatchObject({
            supportsSchemas: false,
            supportsEvents: true,
        });
        expect(capabilitiesOf('mongodb')).toMatchObject({
            supportsDocumentEditor: true,
            supportsProcedures: false,
            supportsERDiagram: false,
            supportsForeignKeys: false,
        });
        expect(capabilitiesOf('nothing').supportsTables).toBe(false);
    });
});

describe('dialects', () => {
    it('quotes names and qualifies tables', () => {
        expect(mysqlDialect.quote('a`b')).toBe('`a``b`');
        expect(postgresDialect.qualify({ schema: 'public', name: 'we"ird' })).toBe(
            '"public"."we""ird"',
        );
        expect(mysqlDialect.qualify({ database: 'shop', name: 'users' })).toBe('`shop`.`users`');
    });

    it('writes values safely', () => {
        expect(postgresDialect.literal({ kind: 'text', value: "O'Brien" })).toBe("'O''Brien'");
        expect(postgresDialect.literal({ kind: 'text', value: 'a\\b' })).toBe("'a\\b'");
        expect(mysqlDialect.literal({ kind: 'text', value: 'a\\b' })).toBe(
            "CONVERT(X'615c62' USING utf8mb4)",
        );
        expect(mysqlDialect.literal({ kind: 'number', value: '1; DROP TABLE x' })).toBe(
            "'1; DROP TABLE x'",
        );
        expect(postgresDialect.literal({ kind: 'binary', hex: 'DEAD' })).toBe("'\\xDEAD'::bytea");
        expect(mysqlDialect.literal({ kind: 'boolean', value: true })).toBe('1');
        expect(postgresDialect.literal({ kind: 'null' })).toBe('NULL');
    });

    it('has no dialect for a document or key-value engine', () => {
        expect(() => dialectOf('mongodb')).toThrow();
    });
});

describe('table designer', () => {
    it('creates a MySQL table with keys and indexes', () => {
        const [create, index] = createTableSql(mysqlDialect, users());
        expect(create).toContain('`id` int NOT NULL AUTO_INCREMENT');
        expect(create).toContain('`email` varchar(255) NOT NULL');
        expect(create).toContain("`bio` text NULL DEFAULT 'none'");
        expect(create).toContain('PRIMARY KEY (`id`)');
        expect(create).toContain('CONSTRAINT `uq_users_email` UNIQUE (`email`)');
        expect(index).toBe('CREATE INDEX `idx_users_bio` ON `users` (`bio`);');
    });

    it('creates a PostgreSQL table with identity, foreign keys and comments', () => {
        const design: TableDesign = {
            ...users(),
            schema: 'public',
            comment: 'People',
            columns: [
                { id: 'a', name: 'id', type: 'integer', nullable: false, autoIncrement: true },
                { id: 'b', name: 'org_id', type: 'integer', nullable: true, comment: 'owner' },
            ],
            uniques: [],
            indexes: [],
            foreignKeys: [
                { columns: ['org_id'], refTable: 'orgs', refColumns: ['id'], onDelete: 'CASCADE' },
            ],
        };
        const sql = createTableSql(postgresDialect, design).join('\n');
        expect(sql).toContain('"id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL');
        expect(sql).toContain(
            'CONSTRAINT "fk_users_org_id" FOREIGN KEY ("org_id") REFERENCES "public"."orgs" ("id") ON DELETE CASCADE',
        );
        expect(sql).toContain('COMMENT ON TABLE "public"."users" IS \'People\'');
        expect(sql).toContain('COMMENT ON COLUMN "public"."users"."org_id" IS \'owner\'');
    });

    it('supports generated columns', () => {
        const design: TableDesign = {
            ...emptyDesign('t'),
            columns: [
                { id: 'a', name: 'a', type: 'int', nullable: false },
                {
                    id: 'b',
                    name: 'b',
                    type: 'int',
                    nullable: false,
                    generated: { expression: '`a` * 2', stored: true },
                },
            ],
        };
        expect(createTableSql(mysqlDialect, design)[0]).toContain(
            '`b` int GENERATED ALWAYS AS (`a` * 2) STORED NOT NULL',
        );
    });

    it('validates a design before generating anything', () => {
        const bad: TableDesign = {
            ...emptyDesign(''),
            columns: [
                { id: 'a', name: 'x', type: 'int', nullable: true },
                { id: 'b', name: 'X', type: 'int', nullable: true },
            ],
            primaryKey: ['missing'],
        };
        const problems = validateDesign(mysqlDialect, bad).join(' ');
        expect(problems).toContain('needs a name');
        expect(problems).toContain('used twice');
        expect(problems).toContain('unknown column');
        expect(validateDesign(mysqlDialect, users())).toEqual([]);
    });

    it('drops tables with options', () => {
        expect(
            dropTableSql(
                postgresDialect,
                { schema: 's', name: 't' },
                { ifExists: true, cascade: true },
            ),
        ).toBe('DROP TABLE IF EXISTS "s"."t" CASCADE;');
    });

    describe('alter', () => {
        it('renames, modifies, adds and drops columns in MySQL', () => {
            const before = users();
            const after: TableDesign = {
                ...before,
                columns: [
                    before.columns[0]!,
                    { ...before.columns[1]!, name: 'mail', length: '320' },
                    { id: 'n', name: 'created', type: 'datetime', nullable: false },
                ],
                uniques: [{ columns: ['mail'] }],
                indexes: [],
            };
            const sql = alterTableSql(mysqlDialect, before, after);
            expect(sql).toContain('ALTER TABLE `users` DROP COLUMN `bio`;');
            expect(sql).toContain(
                'ALTER TABLE `users` CHANGE COLUMN `email` `mail` varchar(320) NOT NULL;',
            );
            expect(sql).toContain('ALTER TABLE `users` ADD COLUMN `created` datetime NOT NULL;');
            // dependents come off before columns change, and the unique key comes back last
            expect(sql.findIndex((x) => x.includes('DROP INDEX `uq_users_email`'))).toBeLessThan(
                sql.findIndex((x) => x.includes('CHANGE COLUMN')),
            );
            expect(
                sql.findIndex((x) => x.includes('ADD CONSTRAINT `uq_users_mail` UNIQUE')),
            ).toBeGreaterThan(sql.findIndex((x) => x.includes('CHANGE COLUMN')));
            expect(sql).toContain('DROP INDEX `idx_users_bio` ON `users`;');
        });

        it('changes one property at a time in PostgreSQL', () => {
            const before: TableDesign = {
                ...emptyDesign('t'),
                schema: 'public',
                columns: [{ id: 'a', name: 'n', type: 'integer', nullable: false }],
            };
            const after: TableDesign = {
                ...before,
                columns: [
                    { id: 'a', name: 'amount', type: 'bigint', nullable: true, default: '0' },
                ],
            };
            const sql = alterTableSql(postgresDialect, before, after);
            expect(sql).toEqual([
                'ALTER TABLE "public"."t" RENAME COLUMN "n" TO "amount";',
                'ALTER TABLE "public"."t" ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;',
                'ALTER TABLE "public"."t" ALTER COLUMN "amount" DROP NOT NULL;',
                'ALTER TABLE "public"."t" ALTER COLUMN "amount" SET DEFAULT 0;',
            ]);
        });

        it('adds and drops foreign keys and renames the table', () => {
            const before = users();
            const after: TableDesign = {
                ...before,
                name: 'people',
                foreignKeys: [
                    { name: 'fk_x', columns: ['id'], refTable: 'orgs', refColumns: ['id'] },
                ],
            };
            const sql = alterTableSql(mysqlDialect, before, after);
            expect(sql).toContain(
                'ALTER TABLE `users` ADD CONSTRAINT `fk_x` FOREIGN KEY (`id`) REFERENCES `orgs` (`id`);',
            );
            expect(sql.at(-1)).toBe('RENAME TABLE `users` TO `people`;');
            const back = alterTableSql(mysqlDialect, after, {
                ...after,
                name: 'people',
                foreignKeys: [],
            });
            expect(back).toContain('ALTER TABLE `people` DROP FOREIGN KEY `fk_x`;');
        });

        it('produces nothing when nothing changed', () => {
            expect(alterTableSql(mysqlDialect, users(), users())).toEqual([]);
            expect(alterTableSql(postgresDialect, users(), users())).toEqual([]);
        });

        it('replaces a changed primary key', () => {
            const before = users();
            const after = { ...before, primaryKey: ['id', 'email'] };
            const sql = alterTableSql(mysqlDialect, before, after);
            expect(sql[0]).toBe('ALTER TABLE `users` DROP PRIMARY KEY;');
            expect(sql.at(-1)).toBe('ALTER TABLE `users` ADD PRIMARY KEY (`id`, `email`);');
        });
    });

    it('builds a design from what the server reported', () => {
        const design = designFromMetadata({
            name: 'orders',
            columns: [
                {
                    name: 'id',
                    position: 1,
                    type: 'int unsigned',
                    nullable: false,
                    primaryKey: true,
                    autoIncrement: true,
                },
                {
                    name: 'total',
                    position: 2,
                    type: 'decimal(10,2)',
                    nullable: false,
                    primaryKey: false,
                    default: '0.00',
                },
                { name: 'user_id', position: 3, type: 'int', nullable: true, primaryKey: false },
            ],
            indexes: [
                { name: 'PRIMARY', columns: ['id'], unique: true, primary: true },
                {
                    name: 'idx_user',
                    columns: ['user_id'],
                    unique: false,
                    primary: false,
                    method: 'BTREE',
                },
            ],
            constraints: [
                { name: 'PRIMARY', kind: 'PRIMARY KEY', columns: ['id'] },
                {
                    name: 'fk_user',
                    kind: 'FOREIGN KEY',
                    columns: ['user_id'],
                    references: { table: 'users', columns: ['id'] },
                    definition: 'ON DELETE CASCADE',
                },
            ],
        });
        expect(design.columns[0]).toMatchObject({
            type: 'int',
            unsigned: true,
            autoIncrement: true,
        });
        expect(design.columns[1]).toMatchObject({
            type: 'decimal',
            length: '10,2',
            default: '0.00',
        });
        expect(design.primaryKey).toEqual(['id']);
        expect(design.foreignKeys[0]).toMatchObject({ refTable: 'users', onDelete: 'CASCADE' });
        expect(design.indexes).toEqual([
            { name: 'idx_user', columns: [{ name: 'user_id' }], unique: false, method: 'BTREE' },
        ]);
        // and the unchanged design generates no statements
        expect(alterTableSql(mysqlDialect, design, structuredClone(design))).toEqual([]);
    });

    it('does not show the index MySQL builds for a foreign key as a design index', () => {
        const design = designFromMetadata({
            name: 'child',
            columns: [
                { name: 'id', position: 1, type: 'int', nullable: false, primaryKey: true },
                { name: 'parent_id', position: 2, type: 'int', nullable: true, primaryKey: false },
            ],
            indexes: [
                { name: 'PRIMARY', columns: ['id'], unique: true, primary: true },
                { name: 'fk_parent', columns: ['parent_id'], unique: false, primary: false },
                { name: 'idx_mine', columns: ['parent_id'], unique: false, primary: false },
            ],
            constraints: [
                {
                    name: 'fk_parent',
                    kind: 'FOREIGN KEY',
                    columns: ['parent_id'],
                    references: { table: 'parent', columns: ['id'] },
                },
            ],
        });
        expect(design.indexes.map((i) => i.name)).toEqual(['idx_mine']);
    });

    it('reads a MySQL string default back as a quoted value, and leaves numbers, keywords and functions', () => {
        const column = (name: string, def: string) => ({
            name,
            position: 1,
            type: 'varchar(9)',
            nullable: true,
            primaryKey: false,
            default: def,
        });
        const read = (def: string, dialect: 'mysql' | 'postgresql') =>
            designFromMetadata({
                dialect,
                name: 't',
                columns: [column('c', def)],
                indexes: [],
                constraints: [],
            }).columns[0]!.default;
        expect(read('none', 'mysql')).toBe("'none'");
        expect(read("it's", 'mysql')).toBe("'it''s'");
        expect(read('0.00', 'mysql')).toBe('0.00');
        expect(read('CURRENT_TIMESTAMP', 'mysql')).toBe('CURRENT_TIMESTAMP');
        expect(read('uuid()', 'mysql')).toBe('uuid()');
        expect(read('(1 + 2)', 'mysql')).toBe('(1 + 2)');
        expect(read("'none'::text", 'postgresql')).toBe("'none'::text");
    });

    it('splits display types', () => {
        expect(splitType('varchar(64)')).toEqual({ type: 'varchar', length: '64' });
        expect(splitType('numeric(10, 2)')).toEqual({ type: 'numeric', length: '10,2' });
        expect(splitType('timestamp with time zone')).toEqual({ type: 'timestamp with time zone' });
        expect(splitType('integer[]')).toEqual({ type: 'integer[]' });
    });

    it('writes indexes per dialect', () => {
        const index = {
            name: 'i',
            columns: [{ name: 'a' }, { name: 'b', order: 'DESC' as const }],
            unique: true,
            method: 'btree',
            where: 'a > 0',
        };
        expect(
            createIndexSql(postgresDialect, { schema: 's', name: 't' }, index, {
                concurrently: true,
            }),
        ).toBe(
            'CREATE UNIQUE INDEX CONCURRENTLY "i" ON "s"."t" USING btree ("a", "b" DESC) WHERE a > 0',
        );
        expect(createIndexSql(mysqlDialect, { name: 't' }, { ...index, where: undefined })).toBe(
            'CREATE UNIQUE INDEX `i` ON `t` (`a`, `b` DESC) USING btree',
        );
    });
});

describe('row editing', () => {
    const table = { schema: 'public', name: 'people' };

    it('pages, filters and sorts on the server', () => {
        const sql = selectPageSql(postgresDialect, {
            table,
            filters: [
                { column: 'name', operator: 'contains', value: '50%_off' },
                { column: 'age', operator: 'gte', value: '18' },
                { column: 'deleted', operator: 'isNull' },
            ],
            rawWhere: 'age < 99',
            sort: [{ column: 'age', direction: 'desc' }],
            limit: 100,
            offset: 200,
        });
        expect(sql).toBe(
            `SELECT *\nFROM "public"."people"\nWHERE "name"::text ILIKE '%50!%!_off%' ESCAPE '!'\n  AND "age" >= '18'\n  AND "deleted" IS NULL\n  AND (age < 99)\nORDER BY "age" DESC\nLIMIT 100 OFFSET 200;`,
        );
        expect(
            selectPageSql(mysqlDialect, {
                table: { name: 't' },
                filters: [],
                sort: [],
                limit: 50,
                offset: 0,
            }),
        ).toBe('SELECT *\nFROM `t`\nLIMIT 50;');
    });

    it('writes single-row changes addressed by key, never touching two rows', () => {
        const key = [{ column: 'id', value: { kind: 'number' as const, value: '7' } }];
        expect(
            updateRowSql(mysqlDialect, { name: 't' }, key, [
                { column: 'name', value: { kind: 'text', value: "x'y" } },
            ]),
        ).toBe("UPDATE `t`\nSET `name` = 'x''y'\nWHERE `id` = 7\nLIMIT 1;");
        expect(deleteRowSql(postgresDialect, table, key)).toBe(
            'DELETE FROM "public"."people"\nWHERE "id" = 7;',
        );
        expect(insertRowSql(mysqlDialect, { name: 't' }, [])).toBe('INSERT INTO `t` () VALUES ();');
        expect(insertRowSql(postgresDialect, table, [])).toBe(
            'INSERT INTO "public"."people" DEFAULT VALUES;',
        );
        expect(() => deleteRowSql(mysqlDialect, { name: 't' }, [])).toThrow(/identified by a key/);
    });

    it('matches a NULL key with IS NULL', () => {
        expect(
            deleteRowSql(mysqlDialect, { name: 't' }, [{ column: 'a', value: { kind: 'null' } }]),
        ).toContain('`a` IS NULL');
    });

    it('reads typed cell input', () => {
        expect(parseCellInput('int', ' 42 ')).toEqual({
            ok: true,
            value: { kind: 'number', value: '42' },
        });
        expect(parseCellInput('int', 'abc').ok).toBe(false);
        expect(parseCellInput('jsonb', '{"a":1}').ok).toBe(true);
        expect(parseCellInput('json', '{oops').ok).toBe(false);
        expect(parseCellInput('bytea', '0xDEADBEEF')).toEqual({
            ok: true,
            value: { kind: 'binary', hex: 'DEADBEEF' },
        });
        expect(parseCellInput('blob', 'xyz').ok).toBe(false);
        expect(parseCellInput('boolean', 'yes')).toEqual({
            ok: true,
            value: { kind: 'boolean', value: true },
        });
        // the word NULL typed into a text cell is text, not a null
        expect(parseCellInput('varchar(10)', 'NULL')).toEqual({
            ok: true,
            value: { kind: 'text', value: 'NULL' },
        });
        expect(categoryOfType('timestamp with time zone')).toBe('temporal');
    });
});

describe('views, routines and triggers', () => {
    it('creates, replaces and drops views per dialect', () => {
        const view = { schema: 'public', name: 'v', query: 'SELECT 1;' };
        expect(createViewSql(postgresDialect, view, { replace: true })).toBe(
            'CREATE OR REPLACE VIEW "public"."v" AS\nSELECT 1;',
        );
        expect(createViewSql(postgresDialect, { ...view, materialized: true })).toBe(
            'CREATE MATERIALIZED VIEW "public"."v" AS\nSELECT 1\nWITH DATA;',
        );
        expect(
            viewQueryFromDefinition(
                'CREATE VIEW `v` AS select 1 AS `x` from `t` WITH CASCADED CHECK OPTION',
            ),
        ).toBe('select 1 AS `x` from `t`');
    });

    it('writes MySQL and PostgreSQL routines differently', () => {
        const routine = {
            name: 'add',
            kind: 'function' as const,
            parameters: [
                { name: 'a', mode: 'IN' as const, type: 'int' },
                { name: 'b', mode: 'IN' as const, type: 'int' },
            ],
            returns: 'int',
            body: 'RETURN a + b;',
            deterministic: true,
        };
        expect(createRoutineSql(mysqlDialect, routine)[0]).toBe(
            'CREATE FUNCTION `add`(`a` int, `b` int)\nRETURNS int\nDETERMINISTIC\nBEGIN\nRETURN a + b;\nEND;',
        );
        const pg = createRoutineSql(
            postgresDialect,
            { ...routine, body: 'BEGIN RETURN a + b; END;' },
            { replace: true },
        )[0]!;
        expect(pg).toContain(
            'CREATE OR REPLACE FUNCTION "add"(IN "a" int, IN "b" int)\nRETURNS int\nLANGUAGE plpgsql\nAS $$',
        );
        // a body that contains $$ gets another tag
        expect(createRoutineSql(postgresDialect, { ...routine, body: "SELECT '$$'" })[0]).toContain(
            'AS $body$',
        );
        expect(
            dropRoutineSql(postgresDialect, {
                name: 'add',
                kind: 'function',
                parameters: routine.parameters,
            }),
        ).toBe('DROP FUNCTION "add"(int, int);');
        expect(dropRoutineSql(mysqlDialect, { name: 'add', kind: 'function' })).toBe(
            'DROP FUNCTION `add`;',
        );
        // MySQL cannot replace: editing drops first
        expect(createRoutineSql(mysqlDialect, routine, { replace: true })[0]).toBe(
            'DROP FUNCTION IF EXISTS `add`;',
        );
    });

    it('runs routines with escaped arguments', () => {
        const parameters = [{ name: 'a', mode: 'IN' as const, type: 'text' }];
        expect(
            callRoutineSql(mysqlDialect, { name: 'p', kind: 'procedure', parameters }, [
                { kind: 'text', value: "it's" },
            ]),
        ).toBe("CALL `p`('it''s');");
        expect(
            callRoutineSql(
                postgresDialect,
                { schema: 's', name: 'f', kind: 'function', parameters },
                [{ kind: 'null' }],
            ),
        ).toBe('SELECT * FROM "s"."f"(NULL);');
    });

    it('calls a MySQL procedure through session variables and reads the outputs back', () => {
        const parameters = [
            { name: 'a', mode: 'IN' as const, type: 'int' },
            { name: 'total', mode: 'OUT' as const, type: 'int' },
            { name: 's', mode: 'INOUT' as const, type: 'varchar(5)' },
        ];
        expect(
            callStatements(
                mysqlDialect,
                { name: 'p', kind: 'procedure', parameters },
                { a: { kind: 'number', value: '5' }, s: { kind: 'text', value: 'x' } },
            ),
        ).toEqual([
            'SET @httpreq_2 = NULL;',
            "SET @httpreq_3 = 'x';",
            'CALL `p`(5, @httpreq_2, @httpreq_3);',
            'SELECT @httpreq_2 AS `total`, @httpreq_3 AS `s`;',
        ]);
        expect(
            callStatements(
                mysqlDialect,
                { name: 'f', kind: 'function', parameters: [parameters[0]!] },
                { a: { kind: 'number', value: '1' } },
            ),
        ).toEqual(['SELECT `f`(1) AS result;']);
        expect(
            callStatements(
                postgresDialect,
                { schema: 's', name: 'p', kind: 'procedure', parameters },
                { a: { kind: 'number', value: '5' }, s: { kind: 'text', value: 'x' } },
            ),
        ).toEqual(['CALL "s"."p"(5, NULL, \'x\');']);
    });

    it('reads parameters out of a definition', () => {
        const params = parametersFromDefinition(
            mysqlDialect,
            'CREATE PROCEDURE `p`(IN a INT, OUT total DECIMAL(10,2), INOUT s VARCHAR(5)) BEGIN END',
        );
        expect(params).toEqual([
            { name: 'a', mode: 'IN', type: 'INT' },
            { name: 'total', mode: 'OUT', type: 'DECIMAL(10,2)' },
            { name: 's', mode: 'INOUT', type: 'VARCHAR(5)' },
        ]);
        expect(
            parametersFromDefinition(
                postgresDialect,
                "CREATE FUNCTION public.f(a integer, b text DEFAULT 'x') RETURNS int",
            ),
        ).toEqual([
            { name: 'a', mode: 'IN', type: 'integer' },
            { name: 'b', mode: 'IN', type: 'text' },
        ]);
    });

    it('writes triggers: a body in MySQL, a function plus a trigger in PostgreSQL', () => {
        const trigger = {
            name: 'audit',
            table: 'orders',
            timing: 'AFTER' as const,
            events: ['INSERT' as const, 'UPDATE' as const],
            body: 'BEGIN RETURN NEW; END;',
            schema: 'public',
        };
        const pg = createTriggerSql(postgresDialect, trigger);
        expect(pg).toHaveLength(2);
        expect(pg[1]).toContain('AFTER INSERT OR UPDATE ON "public"."orders"');
        expect(pg[1]).toContain('EXECUTE FUNCTION "public"."audit_fn"()');
        const my = createTriggerSql(mysqlDialect, {
            ...trigger,
            schema: undefined,
            events: ['INSERT'],
            body: 'SET NEW.x = 1;',
        });
        expect(my[0]).toBe(
            'CREATE TRIGGER `audit`\nAFTER INSERT ON `orders`\nFOR EACH ROW\nBEGIN\nSET NEW.x = 1;\nEND;',
        );
        expect(dropTriggerSql(postgresDialect, trigger)).toBe(
            'DROP TRIGGER "audit" ON "public"."orders";',
        );
        expect(setTriggerEnabledSql(postgresDialect, trigger, false)).toBe(
            'ALTER TABLE "public"."orders" DISABLE TRIGGER "audit";',
        );
        expect(setTriggerEnabledSql(mysqlDialect, trigger, false)).toBeNull();
    });
});

describe('ER model', () => {
    const col = (
        name: string,
        position: number,
        extra: Partial<{ type: string; nullable: boolean; primaryKey: boolean }> = {},
    ) => ({
        name,
        position,
        type: extra.type ?? 'int',
        nullable: extra.nullable ?? true,
        primaryKey: extra.primaryKey ?? false,
    });
    const input = {
        users: {
            name: 'users',
            columns: [col('id', 1, { primaryKey: true, nullable: false })],
            indexes: [],
            constraints: [],
        },
        profiles: {
            name: 'profiles',
            columns: [col('user_id', 1, { nullable: false }), col('bio', 2)],
            indexes: [{ name: 'u', columns: ['user_id'], unique: true, primary: false }],
            constraints: [
                {
                    name: 'fk_profile_user',
                    kind: 'FOREIGN KEY',
                    columns: ['user_id'],
                    references: { table: 'users', columns: ['id'] },
                },
            ],
        },
        posts: {
            name: 'posts',
            columns: [col('id', 1, { primaryKey: true, nullable: false }), col('author', 2)],
            indexes: [],
            constraints: [
                {
                    name: 'fk_post_author',
                    kind: 'FOREIGN KEY',
                    columns: ['author'],
                    references: { table: 'users', columns: ['id'] },
                },
            ],
        },
        tags: {
            name: 'tags',
            columns: [col('id', 1, { primaryKey: true, nullable: false })],
            indexes: [],
            constraints: [],
        },
        post_tags: {
            name: 'post_tags',
            columns: [
                col('post_id', 1, { nullable: false }),
                col('tag_id', 2, { nullable: false }),
            ],
            indexes: [{ name: 'pk', columns: ['post_id', 'tag_id'], unique: true, primary: true }],
            constraints: [
                {
                    name: 'fk_pt_post',
                    kind: 'FOREIGN KEY',
                    columns: ['post_id'],
                    references: { table: 'posts', columns: ['id'] },
                },
                {
                    name: 'fk_pt_tag',
                    kind: 'FOREIGN KEY',
                    columns: ['tag_id'],
                    references: { table: 'tags', columns: ['id'] },
                },
            ],
        },
    };

    it('finds one-to-one, one-to-many and many-to-many relationships', () => {
        const model = buildErModel(Object.values(input));
        const byName = (name: string) => model.relationships.find((r) => r.name === name)!;
        expect(byName('fk_profile_user').cardinality).toBe('one-to-one');
        expect(byName('fk_profile_user').required).toBe(true);
        expect(byName('fk_post_author').cardinality).toBe('one-to-many');
        const m2m = model.relationships.find((r) => r.cardinality === 'many-to-many')!;
        expect([m2m.from.table, m2m.to.table].sort()).toEqual(['posts', 'tags']);
        expect(m2m.viaTable).toBe('post_tags');
        const posts = model.tables.find((t) => t.name === 'posts')!;
        expect(posts.columns.find((c) => c.name === 'author')!.foreignKey).toBe(true);
        expect(relationshipsOf(model, 'users').referencedBy).toHaveLength(2);
    });

    it('infers unconstrained references only on request', () => {
        const loose = [
            {
                name: 'users',
                columns: [col('id', 1, { primaryKey: true })],
                indexes: [],
                constraints: [],
            },
            {
                name: 'orders',
                columns: [col('id', 1, { primaryKey: true }), col('user_id', 2)],
                indexes: [],
                constraints: [],
            },
        ];
        expect(buildErModel(loose).relationships).toHaveLength(0);
        const inferred = buildErModel(loose, { inferMissing: true }).relationships;
        expect(inferred).toHaveLength(1);
        expect(inferred[0]).toMatchObject({
            inferred: true,
            from: { table: 'users' },
            to: { table: 'orders' },
        });
    });

    it('lays out referenced tables to the left of the tables that reference them, even with cycles', () => {
        const model = buildErModel([
            ...Object.values(input),
            {
                name: 'employees',
                columns: [col('id', 1, { primaryKey: true }), col('manager', 2)],
                indexes: [],
                constraints: [
                    {
                        name: 'fk_self',
                        kind: 'FOREIGN KEY',
                        columns: ['manager'],
                        references: { table: 'employees', columns: ['id'] },
                    },
                    {
                        name: 'fk_loop',
                        kind: 'FOREIGN KEY',
                        columns: ['id'],
                        references: { table: 'users', columns: ['id'] },
                    },
                ],
            },
        ]);
        const boxes = autoLayout(model);
        expect(boxes.size).toBe(model.tables.length);
        expect(boxes.get('users')!.x).toBeLessThan(boxes.get('posts')!.x);
        expect(boxes.get('posts')!.x).toBeLessThan(boxes.get('post_tags')!.x);
    });

    it('lays out thousands of tables quickly and without overlap on the same row', () => {
        const many = Array.from({ length: 3000 }, (_, i) => ({
            name: `t${i}`,
            columns: [col('id', 1, { primaryKey: true }), col('parent', 2)],
            indexes: [],
            constraints:
                i > 0
                    ? [
                          {
                              name: `fk${i}`,
                              kind: 'FOREIGN KEY',
                              columns: ['parent'],
                              references: { table: `t${Math.floor(i / 3)}`, columns: ['id'] },
                          },
                      ]
                    : [],
        }));
        const started = Date.now();
        const boxes = autoLayout(buildErModel(many));
        expect(Date.now() - started).toBeLessThan(2000);
        expect(boxes.size).toBe(3000);
        const seen = new Set<string>();
        for (const box of boxes.values()) {
            const key = `${box.x}:${box.y}`;
            expect(seen.has(key)).toBe(false);
            seen.add(key);
        }
    });
});
